# Generated by Django 5.0.1 on 2026-07-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassignmentrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='tickets.ticketcategory'),
        ),
        migrations.AddField(
            model_name='categoryassignmentrule',
            name='executor_groups',
            field=models.ManyToManyField(blank=True, related_name='group_rules', to='tickets.executorgroup'),
        ),
    ]
