# Generated by Django 5.0.1 on 2026-07-19 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('services', '0002_initial'),
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassignmentrule',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executor_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryassignmentrule',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watcher_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='services', to='companies.company'),
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='services', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='service',
            name='ticket_categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='tickets.ticketcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='services', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='service',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryassignmentrule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='services.service'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='services.dayofweek'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.workschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryassignmentrule',
            unique_together={('service', 'category')},
        ),
    ]
