# Generated by Django 5.0.1 on 2026-07-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_and_more'),
        ('services', '0003_initial'),
        ('tickets', '0003_alter_executorgroup_options_and_more'),
        ('users', '0002_alter_permission_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryassignmentrule',
            options={'verbose_name': 'Правило назначения категории', 'verbose_name_plural': 'Правила назначения категорий'},
        ),
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'ordering': ['code'], 'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['name'], 'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='tickets.ticketcategory', verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='executor_groups',
            field=models.ManyToManyField(blank=True, related_name='group_rules', to='tickets.executorgroup', verbose_name='Группы исполнителей'),
        ),
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executor_rules', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='services.service', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watcher_rules', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='code',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='service',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='service',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='services', to='companies.company', verbose_name='Компании'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_services', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.service', verbose_name='Родительский сервис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='services', to='users.userrole', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='service',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.workschedule', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ticket_categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='tickets.ticketcategory', verbose_name='Категории заявок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='services', to='tickets.tickettype', verbose_name='Типы заявок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='service',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='services.dayofweek', verbose_name='Дни недели'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
    ]
