# Generated by Django 5.0.1 on 2026-06-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='generic_dyn_content_080f78_idx'), models.Index(fields=['field_name'], name='generic_dyn_field_n_52f602_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name')},
            },
        ),
    ]
