# Generated by Django 5.0.1 on 2026-06-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dynamicvalue',
            name='generic_dyn_content_080f78_idx',
        ),
        migrations.RemoveIndex(
            model_name='dynamicvalue',
            name='generic_dyn_field_n_52f602_idx',
        ),
        migrations.AlterField(
            model_name='dynamicvalue',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='contenttypes.contenttype'),
        ),
    ]
