# Generated by Django 5.0.1 on 2026-07-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Исходное имя файла'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
