# Generated by Django 5.0.1 on 2026-07-12 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_storedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='storedfile',
            name='mime',
        ),
        migrations.AddField(
            model_name='storedfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
