# Generated by Django 5.0.1 on 2026-07-19 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='tickets.ticketstatus'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='special_users',
            field=models.ManyToManyField(blank=True, related_name='special_notification_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='notifications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['event', 'role', 'channel'], name='notificatio_event_i_b8317d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['event', 'logical_role', 'channel'], name='notificatio_event_i_a9b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['ticket_status', 'role', 'channel'], name='notificatio_ticket__47546c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['ticket_status', 'logical_role', 'channel'], name='notificatio_ticket__8cd0de_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('event', 'role', 'channel'), name='uniq_notification_event_role_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('logical_role__isnull', False)), fields=('event', 'logical_role', 'channel'), name='uniq_notification_event_logical_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('ticket_status', 'role', 'channel'), name='uniq_notification_status_role_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('logical_role__isnull', False)), fields=('ticket_status', 'logical_role', 'channel'), name='uniq_notification_status_logical_channel'),
        ),
    ]
