# Generated by Django 5.0.1 on 2026-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailsettings_created_at_emailsettings_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='event',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text='Каналы доставки (email, push, sms, telegram...)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
