# Generated by Django 5.0.1 on 2026-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='use_ssl',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='use_tls',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='encryption',
            field=models.CharField(choices=[('none', 'Без шифрования'), ('tls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='tls', max_length=20),
        ),
    ]
