# Generated by Django 5.0.1 on 2026-07-20 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_emailsettings_use_ssl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name': 'Настройки электронной почты', 'verbose_name_plural': 'Настройки электронной почты'},
        ),
        migrations.AlterModelOptions(
            name='notificationevent',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Событие уведомления', 'verbose_name_plural': 'События уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['code'], 'verbose_name': 'Шаблон уведомления', 'verbose_name_plural': 'Шаблоны уведомлений'},
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='default_from',
            field=models.EmailField(max_length=254, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='encryption',
            field=models.CharField(choices=[('none', 'Без шифрования'), ('tls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='tls', max_length=20, verbose_name='Шифрование'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(max_length=255, verbose_name='SMTP-сервер'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='port',
            field=models.PositiveIntegerField(default=587, verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text='Список каналов, в которых может использоваться шаблон.', verbose_name='Каналы'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Специальный шаблон'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='special_users',
            field=models.ManyToManyField(blank=True, related_name='special_notification_templates', to=settings.AUTH_USER_MODEL, verbose_name='Специальные получатели'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
