# Generated by Django 5.0.1 on 2026-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationtemplate_body_and_more'),
        ('tickets', '0012_rename_value_string_ticketfieldvalue_value_and_more'),
        ('users', '0011_remove_userfieldvalue_users_userf_user_id_e288c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrule',
            options={'ordering': ['event', 'ticket_status', 'role', 'logical_role', 'channel']},
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='notificatio_event_i_fdc766_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='notificatio_ticket__ba5710_idx',
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('telegram', 'Telegram')], default='telegram', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text='Список каналов, в которых может использоваться шаблон.'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['event', 'role', 'channel'], name='notificatio_event_i_b8317d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['event', 'logical_role', 'channel'], name='notificatio_event_i_a9b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['ticket_status', 'role', 'channel'], name='notificatio_ticket__47546c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['ticket_status', 'logical_role', 'channel'], name='notificatio_ticket__8cd0de_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('event', 'role', 'channel'), name='uniq_notification_event_role_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('logical_role__isnull', False)), fields=('event', 'logical_role', 'channel'), name='uniq_notification_event_logical_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('ticket_status', 'role', 'channel'), name='uniq_notification_status_role_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('logical_role__isnull', False)), fields=('ticket_status', 'logical_role', 'channel'), name='uniq_notification_status_logical_channel'),
        ),
    ]
