# Generated by Django 5.0.1 on 2026-07-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
