# Generated by Django 5.0.1 on 2026-06-02 17:59

import backend.project.tickets.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.project.tickets.utils.upload_paths.ticket_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вложение заявки',
                'verbose_name_plural': 'Вложения заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hide_from_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Комментарий заявки',
                'verbose_name_plural': 'Комментарии заявок',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], default='string', max_length=50)),
                ('relation_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multiple', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('widget', models.CharField(blank=True, max_length=100, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=12)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.CharField(blank=True, max_length=255, null=True)),
                ('max_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_in_list', models.BooleanField(default=False)),
                ('default_expression', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Поле заявки',
                'verbose_name_plural': 'Поля заявки',
            },
        ),
        migrations.CreateModel(
            name='TicketFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='none', max_length=16)),
            ],
            options={
                'ordering': ['field', 'role'],
            },
        ),
        migrations.CreateModel(
            name='TicketFieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Набор полей заявки',
                'verbose_name_plural': 'Наборы полей заявки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['field', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(help_text='Чем меньше число — тем выше приоритет')),
                ('color', models.CharField(default='#cccccc', max_length=7)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('color', models.CharField(default='#999999', max_length=7)),
                ('comment_required', models.BooleanField(default=False)),
                ('blocks_time', models.BooleanField(default=False)),
                ('blocks_editing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['source', 'target'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companies', models.ManyToManyField(blank=True, related_name='executor_groups', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
