# Generated by Django 5.0.1 on 2026-05-25 22:23

import backend.project.tickets.utils.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0004_userlistsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation')], default='string', max_length=50)),
                ('relation_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multiple', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('widget', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(default=12)),
                ('order', models.IntegerField(default=0)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_in_list', models.BooleanField(default=False)),
                ('default_expression', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Поле заявки',
                'verbose_name_plural': 'Поля заявки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketFieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Набор полей заявки',
                'verbose_name_plural': 'Наборы полей заявки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(help_text='Чем меньше число — тем выше приоритет')),
                ('color', models.CharField(default='#cccccc', max_length=7)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('color', models.CharField(default='#999999', max_length=7)),
                ('comment_required', models.BooleanField(default=False)),
                ('blocks_time', models.BooleanField(default=False)),
                ('blocks_editing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companies', models.ManyToManyField(blank=True, related_name='executor_groups', to='companies.company')),
                ('users', models.ManyToManyField(blank=True, related_name='executor_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('executor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.executorgroup')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketpriority')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketstatus')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.project.tickets.utils.upload_paths.ticket_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketfield')),
            ],
            options={
                'verbose_name': 'Вложение заявки',
                'verbose_name_plural': 'Вложения заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.ticketfieldset'),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('fieldset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='tickets.ticketfieldset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hide_from_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Комментарий заявки',
                'verbose_name_plural': 'Комментарии заявок',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__254c10_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='none', max_length=16)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tickets.ticketfield')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_field_accesses', to='users.userrole')),
            ],
            options={
                'ordering': ['field', 'role'],
                'indexes': [models.Index(fields=['field', 'role'], name='tickets_tic_field_i_a5a776_idx'), models.Index(fields=['role'], name='tickets_tic_role_id_d8c752_idx')],
                'unique_together': {('field', 'role')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ticketfield',
            unique_together={('fieldset', 'name')},
        ),
        migrations.CreateModel(
            name='TicketFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tickets.ticketfield')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='tickets.ticket')),
            ],
            options={
                'ordering': ['field', 'id'],
                'indexes': [models.Index(fields=['ticket', 'field'], name='tickets_tic_ticket__99d03f_idx'), models.Index(fields=['field'], name='tickets_tic_field_i_b225fd_idx')],
                'unique_together': {('ticket', 'field')},
            },
        ),
        migrations.CreateModel(
            name='TicketStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='ticket_transitions', to='users.userrole')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='tickets.ticketstatus')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='tickets.ticketstatus')),
            ],
            options={
                'ordering': ['source', 'target'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.ticketpriority')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.tickettype')),
            ],
            options={
                'ordering': ['type', 'priority'],
                'unique_together': {('type', 'priority')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status__20eacd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='tickets_tic_assigne_bcac0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['executor_group'], name='tickets_tic_executo_d1b3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company'], name='tickets_tic_company_73eab5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
    ]
