# Generated by Django 5.2.6 on 2026-07-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0002_initial'),
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executorgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='executor_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='stored_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='generic.storedfile'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketfield'),
        ),
        migrations.AddField(
            model_name='ticketfieldaccess',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tickets.ticketfield'),
        ),
        migrations.AddField(
            model_name='ticketfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.ticketfieldset'),
        ),
        migrations.AddField(
            model_name='ticketfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tickets.ticketfield'),
        ),
        migrations.AddField(
            model_name='ticketfieldvalue',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.ticketpriority'),
        ),
        migrations.AddField(
            model_name='ticketstatustransition',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='ticket_transitions', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='ticketstatustransition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='tickets.ticketstatus'),
        ),
        migrations.AddField(
            model_name='ticketstatustransition',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='tickets.ticketstatus'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='tickets.ticketfieldset'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketfieldaccess',
            unique_together={('field', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketfield',
            unique_together={('fieldset', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticketfieldvalue',
            index=models.Index(fields=['ticket', 'field'], name='tickets_tic_ticket__99d03f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfieldvalue',
            index=models.Index(fields=['field'], name='tickets_tic_field_i_b225fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketfieldvalue',
            unique_together={('ticket', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketstatustransition',
            unique_together={('source', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketsla',
            unique_together={('type', 'priority')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['type'], name='tickets_tic_type_id_400694_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
    ]
