# Generated by Django 5.0.1 on 2026-06-02 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executorgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='executor_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='companies.company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='executor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.executorgroup'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketfield'),
        ),
        migrations.AddField(
            model_name='ticketfieldaccess',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tickets.ticketfield'),
        ),
        migrations.AddField(
            model_name='ticketfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_field_accesses', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.ticketfieldset'),
        ),
        migrations.AddField(
            model_name='ticketfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tickets.ticketfield'),
        ),
        migrations.AddField(
            model_name='ticketfieldvalue',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketpriority'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.ticketpriority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketstatus'),
        ),
        migrations.AddField(
            model_name='ticketstatustransition',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='ticket_transitions', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='ticketstatustransition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='tickets.ticketstatus'),
        ),
        migrations.AddField(
            model_name='ticketstatustransition',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='tickets.ticketstatus'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='tickets.ticketfieldset'),
        ),
        migrations.AddField(
            model_name='ticketsla',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__254c10_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfieldaccess',
            index=models.Index(fields=['field', 'role'], name='tickets_tic_field_i_a5a776_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfieldaccess',
            index=models.Index(fields=['role'], name='tickets_tic_role_id_d8c752_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketfieldaccess',
            unique_together={('field', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketfield',
            unique_together={('fieldset', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticketfieldvalue',
            index=models.Index(fields=['ticket', 'field'], name='tickets_tic_ticket__99d03f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfieldvalue',
            index=models.Index(fields=['field'], name='tickets_tic_field_i_b225fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketfieldvalue',
            unique_together={('ticket', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketstatustransition',
            unique_together={('source', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketsla',
            unique_together={('type', 'priority')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status__20eacd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='tickets_tic_assigne_bcac0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['executor_group'], name='tickets_tic_executo_d1b3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company'], name='tickets_tic_company_73eab5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
    ]
