# Generated by Django 5.0.1 on 2026-07-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_and_more'),
        ('generic', '0003_alter_storedfile_created_at_alter_storedfile_file_and_more'),
        ('tickets', '0002_initial'),
        ('users', '0002_alter_permission_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executorgroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа исполнителей', 'verbose_name_plural': 'Группы исполнителей'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория заявки', 'verbose_name_plural': 'Категории заявок'},
        ),
        migrations.AlterModelOptions(
            name='ticketfieldaccess',
            options={'verbose_name': 'Доступ к полю заявки', 'verbose_name_plural': 'Доступы к полям заявки'},
        ),
        migrations.AlterModelOptions(
            name='ticketfieldvalue',
            options={'ordering': ['field', 'id'], 'verbose_name': 'Значение поля заявки', 'verbose_name_plural': 'Значения полей заявок'},
        ),
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'ordering': ['level'], 'verbose_name': 'Приоритет заявки', 'verbose_name_plural': 'Приоритеты заявок'},
        ),
        migrations.AlterModelOptions(
            name='ticketsla',
            options={'ordering': ['type', 'priority'], 'verbose_name': 'SLA заявки', 'verbose_name_plural': 'SLA заявок'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatustransition',
            options={'ordering': ['source', 'target'], 'verbose_name': 'Переход статуса заявки', 'verbose_name_plural': 'Переходы статусов заявок'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['name'], 'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.AlterField(
            model_name='executorgroup',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='executor_groups', to='companies.company', verbose_name='Компании'),
        ),
        migrations.AlterField(
            model_name='executorgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='executorgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='executorgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='executorgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='executor_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketfield', verbose_name='Поле заявки'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='stored_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='generic.storedfile', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отредактировал'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='hide_from_client',
            field=models.BooleanField(default=False, verbose_name='Скрыть от клиента'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='choices',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('comments', 'Comments'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('file', 'File'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], db_index=True, default='string', max_length=50, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.ticketfieldset', verbose_name='Набор полей'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Текст помощи'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Множественное'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системное поле'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='name',
            field=models.SlugField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подсказка в поле'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательное'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Уникальное значение'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], db_index=True, default='edit', max_length=16, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='ticketfieldaccess',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tickets.ticketfield', verbose_name='Поле заявки'),
        ),
        migrations.AlterField(
            model_name='ticketfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='code',
            field=models.SlugField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Используется по умолчанию'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='ticketfieldset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tickets.ticketfield', verbose_name='Поле заявки'),
        ),
        migrations.AlterField(
            model_name='ticketfieldvalue',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='tickets.ticket', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='level',
            field=models.PositiveIntegerField(help_text='Чем меньше число — тем выше приоритет', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Срок выполнения, часов'),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.ticketpriority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.tickettype', verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='blocks_editing',
            field=models.BooleanField(default=False, verbose_name='Блокирует редактирование'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='blocks_time',
            field=models.BooleanField(default=False, verbose_name='Приостанавливает отсчёт времени'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='#999999', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='comment_required',
            field=models.BooleanField(default=False, verbose_name='Комментарий обязателен'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticketstatustransition',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='ticket_transitions', to='users.userrole', verbose_name='Разрешённые роли'),
        ),
        migrations.AlterField(
            model_name='ticketstatustransition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketstatustransition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='tickets.ticketstatus', verbose_name='Исходный статус'),
        ),
        migrations.AlterField(
            model_name='ticketstatustransition',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='tickets.ticketstatus', verbose_name='Целевой статус'),
        ),
        migrations.AlterField(
            model_name='ticketstatustransition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='tickets.ticketfieldset', verbose_name='Набор полей'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
