# Generated by Django 5.0.1 on 2026-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfield',
            name='section',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
