# Generated by Django 5.0.1 on 2026-05-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticketfield_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketfield',
            options={'verbose_name': 'Поле заявки', 'verbose_name_plural': 'Поля заявки'},
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='relation_entity',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='width',
        ),
    ]
