# Generated by Django 5.0.1 on 2026-05-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketfield_options_remove_ticketfield_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketfield',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='readonly',
        ),
    ]
