# Generated by Django 5.0.1 on 2026-07-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_executorgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивирована'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype', verbose_name='Тип заявки'),
        ),
    ]
