# Generated by Django 5.0.1 on 2026-06-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticketfield_choices_remove_ticketfield_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfield',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='widget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketfield',
            name='width',
            field=models.IntegerField(default=12),
        ),
    ]
