# Generated by Django 5.0.1 on 2026-06-11 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketfield_choices_ticketfield_hidden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_status__20eacd_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_executo_d1b3a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_company_73eab5_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='executor_group',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='readonly',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='relation_entity',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='width',
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], db_index=True, default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['type'], name='tickets_tic_type_id_400694_idx'),
        ),
    ]
