# Generated by Django 5.0.1 on 2026-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketfield_default_value_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_assigne_bcac0e_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='regex',
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
