# Generated by Django 5.0.1 on 2026-06-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_tickets_tic_assigne_bcac0e_idx_and_more'),
        ('users', '0009_alter_userfieldaccess_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketfieldaccess',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticketfieldaccess',
            name='tickets_tic_field_i_a5a776_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketfieldaccess',
            name='tickets_tic_role_id_d8c752_idx',
        ),
        migrations.AlterField(
            model_name='ticketfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
    ]
