# Generated by Django 5.0.1 on 2026-06-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketfield',
            name='default_expression',
        ),
        migrations.RemoveField(
            model_name='ticketfield',
            name='show_in_list',
        ),
    ]
