# Generated by Django 5.0.1 on 2026-07-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketEvent',
        ),
    ]
