# Generated by Django 5.0.1 on 2026-07-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_alter_storedfile_options_and_more'),
        ('tickets', '0015_delete_ticketevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='size',
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='stored_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='generic.storedfile'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('file', 'File'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], db_index=True, default='string', max_length=50),
        ),
    ]
