# Generated by Django 5.0.1 on 2026-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('db_path', models.CharField(blank=True, max_length=500)),
                ('media_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
