# Generated by Django 5.2.6 on 2026-07-18 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed', 'Failed login')], max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('db_path', models.CharField(max_length=500)),
                ('media_path', models.CharField(blank=True, default='', max_length=500)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=50)),
                ('entity', models.CharField(db_index=True, max_length=255)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_repr', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ErrorJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exception', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('traceback', models.TextField()),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
