# Generated by Django 5.0.1 on 2026-06-02 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('db_path', models.CharField(blank=True, max_length=500)),
                ('media_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed', 'Failed login')], max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EntityJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=50)),
                ('entity', models.CharField(db_index=True, max_length=255)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_repr', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
