# Generated by Django 5.0.1 on 2026-06-18 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exception', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('traceback', models.TextField()),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
