# Generated by Django 5.0.1 on 2026-07-20 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authjournal',
            options={'ordering': ['-created'], 'verbose_name': 'Запись журнала авторизации', 'verbose_name_plural': 'Журнал авторизации'},
        ),
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Резервная копия', 'verbose_name_plural': 'Резервные копии'},
        ),
        migrations.AlterModelOptions(
            name='entityjournal',
            options={'ordering': ['-created'], 'verbose_name': 'Запись журнала сущности', 'verbose_name_plural': 'Журнал сущностей'},
        ),
        migrations.AlterModelOptions(
            name='errorjournal',
            options={'ordering': ['-created'], 'verbose_name': 'Запись журнала ошибок', 'verbose_name_plural': 'Журнал ошибок'},
        ),
        migrations.AlterField(
            model_name='authjournal',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('failed', 'Неудачная попытка входа')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='authjournal',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='authjournal',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='authjournal',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='authjournal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='authjournal',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Контрольная сумма'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='db_path',
            field=models.CharField(max_length=500, verbose_name='Путь к базе данных'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='media_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к медиафайлам'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Изменения'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='entity',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='object_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор объекта'),
        ),
        migrations.AlterField(
            model_name='entityjournal',
            name='object_repr',
            field=models.CharField(max_length=500, verbose_name='Представление объекта'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='exception',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Исключение'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='method',
            field=models.CharField(blank=True, max_length=16, verbose_name='HTTP-метод'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Путь запроса'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='traceback',
            field=models.TextField(verbose_name='Трассировка'),
        ),
        migrations.AlterField(
            model_name='errorjournal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
