# Generated by Django 5.0.1 on 2026-05-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_authjournal_entityjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityjournal',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
