# Generated by Django 5.0.1 on 2026-05-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_userlistsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company fieldset',
                'verbose_name_plural': 'Company fieldsets',
            },
        ),
        migrations.CreateModel(
            name='CompanyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation')], default='string', max_length=50)),
                ('relation_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multiple', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('widget', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(default=12)),
                ('order', models.IntegerField(default=0)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='companies.companyfieldset')),
            ],
            options={
                'verbose_name': 'Поле компании',
                'verbose_name_plural': 'Поля компании',
                'ordering': ['order', 'id'],
                'unique_together': {('fieldset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fieldset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companyfieldset')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='none', max_length=16)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='companies.companyfield')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_field_accesses', to='users.userrole')),
            ],
            options={
                'verbose_name': 'Company field access',
                'verbose_name_plural': 'Company field accesses',
                'ordering': ['field', 'role'],
                'indexes': [models.Index(fields=['field', 'role'], name='companies_c_field_i_3e5d3b_idx'), models.Index(fields=['role'], name='companies_c_role_id_61fc46_idx')],
                'unique_together': {('field', 'role')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='companies.company')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='companies.companyfield')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'field'], name='companies_c_company_12a7a9_idx'), models.Index(fields=['field'], name='companies_c_field_i_743c98_idx')],
                'unique_together': {('company', 'field')},
            },
        ),
        migrations.CreateModel(
            name='CompanyListSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('visible_fields', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company list settings',
                'verbose_name_plural': 'Company list settings',
                'ordering': ['entity', 'id'],
                'unique_together': {('user', 'entity')},
            },
        ),
    ]
