# Generated by Django 5.2.6 on 2026-07-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
        migrations.AddField(
            model_name='companyfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='companies.companyfieldset'),
        ),
        migrations.AddField(
            model_name='company',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companyfieldset'),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='companies.companyfield'),
        ),
        migrations.AddField(
            model_name='companylistsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.department', verbose_name='Родительский отдел'),
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfieldaccess',
            unique_together={('field', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='companyfield',
            unique_together={('fieldset', 'name')},
        ),
        migrations.AddIndex(
            model_name='companyfieldvalue',
            index=models.Index(fields=['company', 'field'], name='companies_c_company_12a7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfieldvalue',
            index=models.Index(fields=['field'], name='companies_c_field_i_743c98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfieldvalue',
            unique_together={('company', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='companylistsettings',
            unique_together={('user', 'entity')},
        ),
    ]
