# Generated by Django 5.0.1 on 2026-07-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('users', '0002_alter_permission_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='companyfieldaccess',
            options={'verbose_name': 'Доступ к полю компании', 'verbose_name_plural': 'Доступы к полям компании'},
        ),
        migrations.AlterModelOptions(
            name='companyfieldset',
            options={'verbose_name': 'Набор полей компании', 'verbose_name_plural': 'Наборы полей компаний'},
        ),
        migrations.AlterModelOptions(
            name='companyfieldvalue',
            options={'verbose_name': 'Значение поля компании', 'verbose_name_plural': 'Значения полей компаний'},
        ),
        migrations.AlterModelOptions(
            name='companylistsettings',
            options={'ordering': ['entity', 'id'], 'verbose_name': 'Настройки списка компаний', 'verbose_name_plural': 'Настройки списков компаний'},
        ),
        migrations.AlterField(
            model_name='company',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companyfieldset', verbose_name='Набор полей'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='choices',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('comments', 'Comments'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('file', 'File'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], db_index=True, default='string', max_length=50, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='companies.companyfieldset', verbose_name='Набор полей'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Текст помощи'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Множественное'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системное поле'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='name',
            field=models.SlugField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подсказка в поле'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательное'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Уникальное значение'),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='companyfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], db_index=True, default='edit', max_length=16, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='companyfieldaccess',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='companies.companyfield', verbose_name='Поле компании'),
        ),
        migrations.AlterField(
            model_name='companyfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='code',
            field=models.SlugField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Используется по умолчанию'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='companyfieldset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='companyfieldvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='companies.companyfield', verbose_name='Поле компании'),
        ),
        migrations.AlterField(
            model_name='companylistsettings',
            name='entity',
            field=models.CharField(max_length=255, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='companylistsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='companylistsettings',
            name='visible_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Видимые поля'),
        ),
    ]
