# Generated by Django 5.0.1 on 2026-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone')], default='string', max_length=50),
        ),
    ]
