# Generated by Django 5.0.1 on 2026-05-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyfield_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfield',
            options={'verbose_name': 'Поле компании', 'verbose_name_plural': 'Поля компании'},
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='relation_entity',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='width',
        ),
    ]
