# Generated by Django 5.0.1 on 2026-05-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companyfield_options_remove_companyfield_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfield',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='readonly',
        ),
    ]
