# Generated by Django 5.0.1 on 2026-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyfield_choices_companyfield_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfield',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='readonly',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='relation_entity',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='width',
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], db_index=True, default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
