# Generated by Django 5.0.1 on 2026-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_companyfield_hidden_remove_companyfield_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
