# Generated by Django 5.0.1 on 2026-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_companyfield_default_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfield',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='companyfield',
            name='regex',
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyfield',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
