# Generated by Django 5.0.1 on 2026-06-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_companyfield_default_value_and_more'),
        ('users', '0009_alter_userfieldaccess_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
    ]
