# Generated by Django 5.0.1 on 2026-06-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companyfieldaccess_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
    ]
