# Generated by Django 5.0.1 on 2026-06-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_company_created_at_remove_company_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyfieldvalue',
            name='companies_c_company_12a7a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='companyfieldvalue',
            name='companies_c_field_i_743c98_idx',
        ),
        migrations.RenameField(
            model_name='companyfieldvalue',
            old_name='value_string',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_boolean',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_datetime',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_json',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_number',
        ),
    ]
