# Generated by Django 5.0.1 on 2026-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_companyfieldvalue_companies_c_company_12a7a9_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfieldvalue',
            old_name='value',
            new_name='value_string',
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='value_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='companyfieldvalue',
            index=models.Index(fields=['company', 'field'], name='companies_c_company_12a7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfieldvalue',
            index=models.Index(fields=['field'], name='companies_c_field_i_743c98_idx'),
        ),
    ]
