# Generated by Django 5.0.1 on 2026-06-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_rename_value_companyfieldvalue_value_string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfieldvalue',
            old_name='value_string',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_boolean',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_datetime',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_json',
        ),
        migrations.RemoveField(
            model_name='companyfieldvalue',
            name='value_number',
        ),
    ]
