# Generated by Django 5.0.1 on 2026-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], max_length=16),
        ),
    ]
