# Generated by Django 5.0.1 on 2026-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_alter_companyfield_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfieldaccess',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='companyfieldaccess',
            name='companies_c_field_i_3e5d3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='companyfieldaccess',
            name='companies_c_role_id_61fc46_idx',
        ),
        migrations.AlterField(
            model_name='companyfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], db_index=True, default='edit', max_length=16),
        ),
    ]
