# Generated by Django 5.2.6 on 2026-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB', '0002_alter_article_options_alter_articlesection_options_and_more'),
        ('users', '0002_alter_permission_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesection',
            options={'ordering': ['name'], 'verbose_name': 'Раздел базы знаний', 'verbose_name_plural': 'Разделы базы знаний'},
        ),
        migrations.RemoveField(
            model_name='articlesection',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='articlesection',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='articlesection',
            name='user_roles',
            field=models.ManyToManyField(blank=True, related_name='article_sections', to='users.userrole', verbose_name='Роли пользователей'),
        ),
    ]
