# Generated by Django 5.2.6 on 2026-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB', '0003_alter_articlesection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
