# Generated by Django 5.2.6 on 2026-07-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB', '0004_article_is_readonly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Статья базы знаний', 'verbose_name_plural': 'Статьи базы знаний'},
        ),
        migrations.AlterModelOptions(
            name='articlesection',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Раздел базы знаний', 'verbose_name_plural': 'Разделы базы знаний'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_readonly',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
