# Generated by Django 5.0.1 on 2026-06-02 17:59

import backend.project.users.managers.user_manager
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserFieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], default='string', max_length=50)),
                ('relation_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multiple', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('widget', models.CharField(blank=True, max_length=100, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=12)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.CharField(blank=True, max_length=255, null=True)),
                ('max_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.userfieldset')),
            ],
            options={
                'unique_together': {('fieldset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('fieldset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userfieldset')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userrole')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', backend.project.users.managers.user_manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='users.userfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
        migrations.CreateModel(
            name='UserListSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('visible_fields', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='UserFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='none', max_length=16)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.userfield')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_accesses', to='users.userrole')),
            ],
            options={
                'unique_together': {('field', 'role')},
            },
        ),
    ]
