# Generated by Django 5.0.1 on 2026-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfieldaccess',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='userfieldaccess',
            name='can_view',
        ),
        migrations.AddField(
            model_name='userfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Просмотр'), ('edit', 'Редактирование')], default='none', max_length=16),
        ),
    ]
