# Generated by Django 5.0.1 on 2026-07-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['category', 'code'], 'verbose_name': 'Разрешение', 'verbose_name_plural': 'Разрешения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userfield',
            options={'verbose_name': 'Поле пользователя', 'verbose_name_plural': 'Поля пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userfieldaccess',
            options={'verbose_name': 'Доступ к полю пользователя', 'verbose_name_plural': 'Доступы к полям пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userfieldset',
            options={'verbose_name': 'Набор полей пользователя', 'verbose_name_plural': 'Наборы полей пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userfieldvalue',
            options={'verbose_name': 'Значение поля пользователя', 'verbose_name_plural': 'Значения полей пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userlistsettings',
            options={'verbose_name': 'Настройки списка пользователя', 'verbose_name_plural': 'Настройки списков пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['name'], 'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userfieldset', verbose_name='Набор полей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='choices',
            field=models.JSONField(blank=True, default=list, verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('richtext', 'RichText'), ('comments', 'Comments'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('file', 'File'), ('relation', 'Relation'), ('email', 'Email'), ('phone', 'Phone'), ('password', 'Password'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ticket', 'Ticket'), ('status', 'Status'), ('priority', 'Priority')], db_index=True, default='string', max_length=50, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.userfieldset', verbose_name='Набор полей'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Текст помощи'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Множественное'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системное поле'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='name',
            field=models.SlugField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подсказка в поле'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательное'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Уникальное значение'),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], db_index=True, default='edit', max_length=16, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='userfieldaccess',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.userfield', verbose_name='Поле пользователя'),
        ),
        migrations.AlterField(
            model_name='userfieldaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='code',
            field=models.SlugField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Используется по умолчанию'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='users.userfield', verbose_name='Поле пользователя'),
        ),
        migrations.AlterField(
            model_name='userfieldvalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userlistsettings',
            name='entity',
            field=models.CharField(max_length=255, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='userlistsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userlistsettings',
            name='visible_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Видимые поля'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_executor',
            field=models.BooleanField(default=False, verbose_name='Роль исполнителя'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='Разрешения'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
