# Generated by Django 5.0.1 on 2026-06-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfield_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='readonly',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='width',
        ),
    ]
