# Generated by Django 5.0.1 on 2026-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userfield_choices_remove_userfield_hidden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfieldset',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='fieldsets', to='users.userfield'),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='fieldset',
        ),
    ]
