# Generated by Django 5.0.1 on 2026-05-26 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userlistsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userfieldset'),
        ),
    ]
