# Generated by Django 5.0.1 on 2026-06-10 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userfieldset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfieldset',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='userfieldset',
            name='fields',
        ),
        migrations.AddField(
            model_name='userfield',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userfield',
            name='fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.userfieldset'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfield',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfield',
            name='widget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='width',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfieldset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userfieldset',
            name='code',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='userfield',
            unique_together={('fieldset', 'name')},
        ),
    ]
