# Generated by Django 5.0.1 on 2026-05-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userfield_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfield',
            options={},
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='relation_entity',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='width',
        ),
    ]
