# Generated by Django 5.0.1 on 2026-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userfield_hidden_remove_userfield_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfieldset',
            options={},
        ),
        migrations.AlterField(
            model_name='userfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
