# Generated by Django 5.0.1 on 2026-05-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userfield_options_remove_userfield_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfield',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='readonly',
        ),
    ]
