# Generated by Django 5.0.1 on 2026-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userfieldaccess_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfieldvalue',
            old_name='value',
            new_name='value_string',
        ),
        migrations.AddField(
            model_name='userfieldvalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfieldvalue',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfieldvalue',
            name='value_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfieldvalue',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='userfieldvalue',
            index=models.Index(fields=['user', 'field'], name='users_userf_user_id_e288c1_idx'),
        ),
        migrations.AddIndex(
            model_name='userfieldvalue',
            index=models.Index(fields=['field'], name='users_userf_field_i_f3b82e_idx'),
        ),
    ]
