# Generated by Django 5.0.1 on 2026-06-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_value_userfieldvalue_value_string_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userfieldvalue',
            name='users_userf_user_id_e288c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='userfieldvalue',
            name='users_userf_field_i_f3b82e_idx',
        ),
        migrations.RenameField(
            model_name='userfieldvalue',
            old_name='value_string',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='userfieldvalue',
            name='value_boolean',
        ),
        migrations.RemoveField(
            model_name='userfieldvalue',
            name='value_datetime',
        ),
        migrations.RemoveField(
            model_name='userfieldvalue',
            name='value_json',
        ),
        migrations.RemoveField(
            model_name='userfieldvalue',
            name='value_number',
        ),
    ]
