# Generated by Django 5.0.1 on 2026-07-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userfieldvalue_users_userf_user_id_e288c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='priority',
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_executor',
            field=models.BooleanField(default=False),
        ),
    ]
