# Generated by Django 5.0.1 on 2026-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userrole_options_remove_userrole_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], max_length=16),
        ),
    ]
