# Generated by Django 5.0.1 on 2026-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfieldaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], db_index=True, default='edit', max_length=16),
        ),
    ]
